<!DOCTYPE html>
<html>
    <head>
        <title>Hello</title>
    </head>
    <style type="text/css">
    	* {
    		margin: 0;
    		padding: 0;
    	}
    	html,body,div {
    		width: 100%;
    		height: 100%;
    		text-align: center;
    	}

    	div {
    		line-height: 600px;
    		font-family: "Microsoft YaHei",Helvetica,Arial,sans-serif;
    		font-size: 72px;
    		color: #f60;
    		font-weight: lighter;
    	}

    </style>
    <body>
        <div>Hello <?php echo $hello; ?></div>
    </body>
</html>