<!DOCTYPE html>
<html>
    <head>
        <title>Hello</title>
    </head>
    <style type="text/css">
    	* {
    		margin: 0;
    		padding: 0;
    	}
    	html,body,div,p {
    		width: 100%;
    		text-align: center;
    	}

    	div {
            height: 400px;
    		line-height: 650px;
    		font-family: "Microsoft YaHei",Helvetica,Arial,sans-serif;
    		font-size: 72px;
    		color: #f60;
    		font-weight: lighter;
            overflow: hidden;
    	}
        p {
            height: 30px;
            line-height: 30px;
            font-family: "Microsoft YaHei",Helvetica,Arial,sans-serif;
            font-size: 16px;
            color: #bbb;
            font-weight: lighter;
        }
    </style>
    <body>
        <div>Hello <?php echo $hello; ?></div>
        <p>Version: <?php echo EDOGER_VERSION; ?></p>
    </body>
</html>